---
- hosts: local
  connection: local
  gather_facts: False
  become: True
  tasks:

  - name: Download Default Key Pair
    shell: "aws --region {{prefer region}} lightsail download-default-key-pair > ~/lightsail-key.json"

  - name: Modify Private Key Permissions
    command: "chmod 600 ~/lightsail-key.json"
 
  - set_fact:
      ansible_facts:
        pkg_mgr: yum _

  roles:
    - lightsail-docker
    - Common
    - docker
