---

- name: Create a Lightsail instance
  lightsail:
    state: present
    name: {{Instance name}}
    region: {{your region}}
    zone: {{your zone}}
    blueprint_id: {{instance type}}
    bundle_id: {{price type}}
    wait_timeout: 500
  register: _lightsail_instance
- debug:
    var: _lightsail_instance

- name: Download Default Key Pair  
  shell: "aws lightsail attach-static-ip --static-ip-name {{staticIP}} --instance-name {{Instance name}}  --region {{your region}}"

